// app/layout.js
import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";

// THIS IS THE NEW, CLEAN IMPORT PATH:
import { authOptions } from "./lib/authOptions"; 

import SessionProvider from "./components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}